loadable_midis = { ...
'midi files/beeth/appass_1.mid', ...
'midi files/beeth/beethoven_hammerklavier_1.mid', ...
'midi files/beeth/beethoven_opus22_1.mid', ...
'midi files/beeth/beethoven_opus22_4.mid', ...
'midi files/beeth/mond_3.mid', ...
'midi files/chopin/chpn-p10.mid', ...
'midi files/chopin/chpn-p11.mid', ...
'midi files/chopin/chpn-p7.mid', ...
'midi files/chopin/chpn_op10_e05.mid', ...
'midi files/chopin/chpn_op10_e12.mid', ...
'midi files/chopin/chpn_op23.mid', ...
'midi files/chopin/chpn_op35_2.mid', ...
'midi files/debussy/DEB_CLAI.MID', ...
'midi files/debussy/deb_prel.mid', ...
'midi files/joplin/cascades.mid', ...
'midi files/joplin/felicity.mid', ...
'midi files/joplin/gladiolus.mid', ...
'midi files/joplin/kismet.mid', ...
'midi files/joplin/lily_queen.mid', ...
'midi files/joplin/magnetic_rag.mid', ...
'midi files/joplin/new_rag.mid', ...
'midi files/joplin/nonpareil.mid', ...
'midi files/joplin/original.mid', ...
'midi files/joplin/palm_leaf.mid', ...
'midi files/joplin/peacherine.mid', ...
'midi files/joplin/pineapple.mid', ...
'midi files/joplin/ragtime_dance.mid', ...
'midi files/joplin/something_doing.mid', ...
'midi files/joplin/sunflower.mid', ...
'midi files/joplin/twostep.mid', ...
'midi files/joplin/wall_street.mid', ...
'midi files/joplin/weepwilo.mid', ...
'midi files/lamb/AmericanBeautyRag.midi', ...
'midi files/lamb/bohemia.midi', ...
'midi files/lamb/champagn.midi', ...
'midi files/lamb/contentm.midi', ...
'midi files/lamb/excelsr.midi', ...
'midi files/lamb/reindeer.midi', ...
'midi files/lamb/topliner.midi', ...
'midi files/schubert/schubert_D850_2.mid', ...
'midi files/schubert/schuim-2.mid', ...
'midi files/schubert/schuim-4.mid', ...
'midi files/schubert/schumm-1.mid', ...
'midi files/scott (james)/broadway.midi', ...
'midi files/scott (james)/dnjazzme.midi', ...
'midi files/scott (james)/efficncy.midi', ...
'midi files/scott (james)/evergren.midi', ...
'midi files/scott (james)/froglegs.midi', ...
'midi files/scott (james)/greatsct.midi', ...
'midi files/scott (james)/hilarity.midi', ...
'midi files/scott (james)/kansascy.midi', ...
'midi files/scott (james)/newera.midi', ...
'midi files/scott (james)/peacepln.midi', ...
'midi files/scott (james)/qualtrag.midi', ...
'midi files/scott (james)/ragoriol.midi', ...
'midi files/scott (james)/sunburst.midi', ...
'midi files/scott (james)/victory.midi'};
